# Definiert das AddOn, grundlegende Einstellungen - Diese Detei ist unbedingt erforderlich
# Dokumentation der `package.yml` https://redaxo.org/doku/master/addon-package
# Alle hier gesetzten Werte können über `$addon->getProperty($key)` abgefragt werden

package: dbac # Pflichtfeld
version: "1.1.3" # Pflichtfeld
author: Loris Vonlanthen # Pflichtfeld für FOR-AddOns
supportpage: https://etrex.ch # Github-Adresse des AddOns

requires:
  redaxo: "^5.15.0"
  php:
    version: ">7"
  packages:
    mediapool: "^2.6.0"
    metainfo: "^2.6.0"
    flatpickr: "^1.1.0"
    developer: "^3.6.0"
    bloecks: "^4.0.0"

default_config:
  mediapool: true
  page: true

# Werte die mit `translate:` beginnen, werden anhand der Sprachdatei (lang/sprache.lang) übersetzt.
# Der AddOn-Präfix (hier `dbac_`) kann weggelassen werden.

# Seiten des AddOns
page:
  title: "translate:dbac_title" # Bezeichnung in der REDAXO Navigation
  icon: rex-icon fa-eye-slash # Icon von Font Awesome
  perm: admin # Seite ist nur für Admins erreichbar
  pjax: true # Hier kann die Verwendung von PJAX für das eigene AddOn gesteuert werden
  # mit der Einstellung `prio` kann die Position im Hauptmenü beeinflusst werden
  #prio: 10

  # Unterseiten
  subpages:
    intro:
      title: "translate:dbac_title"
      icon: rex-icon fa-eye-slash # Icon von Font Awesome
      perm: dbac[] # Das AddOn stellt ein Benutzerrecht bereit, das aktiviert sein muss, um diese Unterseite zu erreichen. Admins haben alle Rechte.
      subpages: # Weitere Subpages der Hauptseite
        description:
          {
            title: "translate:dbac_description",
            subPath: "pages/DESCRIPTION.md",
          }
        config:
          {
            title: "translate:dbac_config",
            subPath: "pages/config.rex_config_form.php",
          }
        changelog:
          { title: "translate:dbac_changelog", subPath: "pages/CHANGELOG.md" }

# Installer (ab REX 5.7)
# Angabe von Ordnern und Dateien, die vom Installer ausgelassen werden sollen, wenn ein Release veröffentlicht wird
# Siehe auch https://github.com/redaxo/redaxo/pull/2352
installer_ignore:
  - node_modules
  - .env
